/// Abstract interface matching the Rust core API surface.
///
/// The real implementation is [BridgeFrb] (generated by flutter_rust_bridge after
/// running `flutter_rust_bridge_codegen generate` in this directory). During
/// development without the generated bindings, use [BridgeStub] instead.
library;

class CalendarView {
  const CalendarView({
    required this.id,
    required this.displayName,
    required this.source,
    this.lastSyncedAt,
  });

  final String id;
  final String displayName;

  /// "local", "caldav", "subscription"
  final String source;
  final DateTime? lastSyncedAt;

  bool get isLocal => source == 'local';
  bool get isCalDav => source == 'caldav';
}

class OccurrenceView {
  const OccurrenceView({
    required this.eventId,
    required this.calendarId,
    required this.summary,
    this.description,
    this.location,
    required this.dtstart,
    required this.dtend,
    required this.isAllDay,
    this.timezone,
    required this.hasRecurrence,
    this.recurrenceIdMs,
    required this.status,
  });

  final String eventId;
  final String calendarId;
  final String summary;
  final String? description;
  final String? location;
  final DateTime dtstart;
  final DateTime dtend;
  final bool isAllDay;
  final String? timezone;
  final bool hasRecurrence;
  final int? recurrenceIdMs;

  /// "confirmed", "tentative", "cancelled"
  final String status;
}

class EventDraft {
  const EventDraft({
    required this.summary,
    this.description,
    this.location,
    required this.dtstart,
    required this.dtend,
    required this.isAllDay,
    this.timezone,
    this.rrule,
  });

  final String summary;
  final String? description;
  final String? location;
  final DateTime dtstart;
  final DateTime dtend;
  final bool isAllDay;
  final String? timezone;
  final String? rrule;
}

class EventPatch {
  const EventPatch({
    this.summary,
    this.description,
    this.location,
    this.dtstart,
    this.dtend,
    this.isAllDay,
    this.timezone,
    this.rrule,
  });

  final String? summary;
  // Wrapped in a record to distinguish "no update" from "set to null".
  final (String?,)? description;
  final (String?,)? location;
  final DateTime? dtstart;
  final DateTime? dtend;
  final bool? isAllDay;
  final (String?,)? timezone;
  final (String?,)? rrule;
}

enum DeleteScope { thisOnly, thisAndFuture, all }

class SyncResult {
  const SyncResult({
    required this.fetched,
    required this.deleted,
    required this.errors,
  });

  final int fetched;
  final int deleted;
  final List<String> errors;
}

abstract class Bridge {
  Future<void> init(String dbPath);

  Future<List<CalendarView>> listCalendars();
  Future<String> createLocalCalendar(String displayName);
  Future<List<String>> addCalDavAccount({
    required String baseUrl,
    required String username,
    required String password,
  });

  Future<List<OccurrenceView>> occurrencesInRange({
    required List<String> calendarIds,
    required DateTime start,
    required DateTime end,
  });

  Future<String> createEvent(String calendarId, EventDraft draft);
  Future<void> updateEvent(String eventId, EventPatch patch);
  Future<void> deleteEvent(
    String eventId,
    DeleteScope scope, {
    int? recurrenceIdMs,
  });

  Future<SyncResult> syncNow(String calendarId);
}
